// Central config for every content module. The generic ModulePage component
// reads this to render the right table columns + add/edit form fields,
// and talks to the matching backend controller (endpoint).
//
// field.type: text | textarea | number | date | checkbox | file
// field.image: true -> shows an image preview + counts as the "thumb" column

export const modules = {
  media: {
    key: 'media',
    label: 'Media Library',
    icon: 'bi-collection-play',
    color: '#0f766e',
    endpoint: '/media',
    titleField: 'title',
    imageField: null,
    fileField: 'filePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'altText', label: 'Alt Text', type: 'text', full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'file', label: 'Image / PDF / Document', type: 'file', requiredOnCreate: true, hint: 'JPG, PNG, WEBP, GIF, PDF, DOC, DOCX; maximum 10 MB.' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'fileType', label: 'Type' },
      { key: 'category', label: 'Category' },
      { key: 'file', label: 'File' },
      { key: 'status', label: 'Status' },
    ],
  },

  pages: {
    key: 'pages',
    label: 'Pages / Content',
    icon: 'bi-file-richtext',
    color: '#334155',
    endpoint: '/contentpages',
    titleField: 'title',
    imageField: 'coverImagePath',
    fields: [
      { name: 'slug', label: 'Page Slug', type: 'text', hint: 'Example: vision-and-mission' },
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', full: true },
      { name: 'body', label: 'Page Content', type: 'richtext', required: true, full: true },
      { name: 'metaTitle', label: 'Meta Title', type: 'text', full: true },
      { name: 'metaDescription', label: 'Meta Description', type: 'textarea', full: true },
      { name: 'coverAltText', label: 'Cover Image Alt Text', type: 'text', full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'coverImage', label: 'Cover Image', type: 'file', image: true, accept: 'image/jpeg,image/png,image/webp,image/gif' },
    ],
    columns: [
      { key: 'thumb', label: 'Cover' },
      { key: 'title', label: 'Title' },
      { key: 'slug', label: 'Slug' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status' },
    ],
  },

  about: {
    key: 'about',
    label: 'About',
    icon: 'bi-info-circle',
    color: '#2f6fed',
    endpoint: '/about',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: false, full: true },
      { name: 'description', label: 'Description', type: 'richtext', required: true, full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', required: true, default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'showOnHomePage', label: 'Home Page', type: 'checkbox', group: 'Show On Website' },
      { name: 'showOnAboutPage', label: 'About Page', type: 'checkbox', group: 'Show On Website' },
      { name: 'showOnFooter', label: 'Footer', type: 'checkbox', group: 'Show On Website' },
      { name: 'showOnVisionMission', label: 'Vision & Mission', type: 'checkbox', group: 'Show On Website' },
      { name: 'showOnRoleOfSJMC', label: 'Role of SJMC', type: 'checkbox', group: 'Show On Website' },
      { name: 'showOnFounderDirector', label: 'Founder Director', type: 'checkbox', group: 'Show On Website' },
      { name: 'image', label: 'Image', type: 'file', image: true, hint: 'Recommended size: 1200x600' },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
      { key: 'showOn', label: 'Show On' },
    ],
  },

  faculty: {
    key: 'faculty',
    label: 'Faculty',
    icon: 'bi-people',
    color: '#16a34a',
    endpoint: '/faculty',
    titleField: 'name',
    imageField: 'photoPath',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'qualification', label: 'Qualification', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'bio', label: 'Bio', type: 'richtext', full: true },
      { name: 'showOnFacultyPage', label: 'Faculty Page (Head)', type: 'checkbox', group: 'Show On Website' },
      { name: 'showOnGuestFaculty', label: 'Guest Faculty', type: 'checkbox', group: 'Show On Website' },
      { name: 'showOnConsultant', label: 'Consultant', type: 'checkbox', group: 'Show On Website' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'photo', label: 'Photo', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Photo' },
      { key: 'name', label: 'Name' },
      { key: 'designation', label: 'Designation' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  staff: {
    key: 'staff',
    label: 'Staff',
    icon: 'bi-person-badge',
    color: '#f59e0b',
    endpoint: '/staff',
    titleField: 'name',
    imageField: 'photoPath',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'photo', label: 'Photo', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Photo' },
      { key: 'name', label: 'Name' },
      { key: 'designation', label: 'Designation' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  gallery: {
    key: 'gallery',
    label: 'Gallery',
    icon: 'bi-image',
    color: '#8b5cf6',
    endpoint: '/gallery',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'altText', label: 'Alt Text', type: 'text', full: true, hint: 'Describe the image for accessibility and SEO.' },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'linkUrl', label: 'Detail Page URL', type: 'text', hint: 'Optional, for example /Annual_Day' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Image', type: 'file', image: true, requiredOnCreate: true, accept: 'image/jpeg,image/png,image/webp,image/gif', hint: 'JPG, PNG, WEBP, or GIF; maximum 5 MB.' },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  news: {
    key: 'news',
    label: 'News',
    icon: 'bi-newspaper',
    color: '#ef4444',
    endpoint: '/news',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'publishDate', label: 'Publish Date', type: 'date', default: 'today' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Image', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'publishDate', label: 'Publish Date', date: true },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  events: {
    key: 'events',
    label: 'Events',
    icon: 'bi-calendar-event',
    color: '#06b6d4',
    endpoint: '/events',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'eventDate', label: 'Event Date', type: 'date', default: 'today' },
      { name: 'venue', label: 'Venue', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Image', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'eventDate', label: 'Event Date', date: true },
      { key: 'venue', label: 'Venue' },
      { key: 'status', label: 'Status' },
    ],
  },

  notice: {
    key: 'notice',
    label: 'Notice',
    icon: 'bi-megaphone',
    color: '#ec4899',
    endpoint: '/notice',
    titleField: 'title',
    imageField: null,
    fileField: 'filePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'noticeDate', label: 'Notice Date', type: 'date', default: 'today' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'file', label: 'Attachment (PDF)', type: 'file', hint: 'PDF, DOC allowed' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'noticeDate', label: 'Notice Date', date: true },
      { key: 'file', label: 'File' },
      { key: 'status', label: 'Status' },
    ],
  },

  slider: {
    key: 'slider',
    label: 'Slider',
    icon: 'bi-images',
    color: '#f59e0b',
    endpoint: '/slider',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'linkUrl', label: 'Link URL', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Slide Image', type: 'file', image: true, requiredOnCreate: true, hint: 'Recommended size: 1920x700' },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  courses: {
    key: 'courses',
    label: 'Courses',
    icon: 'bi-mortarboard',
    color: '#111827',
    endpoint: '/courses',
    titleField: 'name',
    imageField: 'imagePath',
    fields: [
      { name: 'name', label: 'Course Name', type: 'text', required: true, full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'duration', label: 'Duration', type: 'text' },
      { name: 'eligibility', label: 'Eligibility', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Image', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'name', label: 'Course' },
      { key: 'duration', label: 'Duration' },
      { key: 'status', label: 'Status' },
    ],
  },

  downloads: {
    key: 'downloads',
    label: 'Downloads',
    icon: 'bi-download',
    color: '#0d9488',
    endpoint: '/downloads',
    titleField: 'title',
    imageField: null,
    fileField: 'filePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'file', label: 'File', type: 'file', requiredOnCreate: true },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'file', label: 'File' },
      { key: 'status', label: 'Status' },
    ],
  },

  publications: {
    key: 'publications',
    label: 'Publications',
    icon: 'bi-journal-text',
    color: '#065f46',
    endpoint: '/publications',
    titleField: 'title',
    imageField: null,
    fileField: 'filePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'publishYear', label: 'Publish Year', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'file', label: 'File', type: 'file' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'author', label: 'Author' },
      { key: 'publishYear', label: 'Year' },
      { key: 'status', label: 'Status' },
    ],
  },
};

export const moduleList = Object.values(modules);